CREATE TABLE [dbo].[PadronElectoral]
(
		IdCivil INT NOT NULL IDENTITY(1,1) CONSTRAINT PK_Civil PRIMARY KEY CLUSTERED(IdCivil)
	, Cedula VARCHAR (15) NOT NULL
	, Nombre VARCHAR (50) NOT NULL
	, Apellido1 VARCHAR (150) NOT NULL
	, Apellido2  VARCHAR (150) NOT NULL
	, Edad int NOT NULL
		CONSTRAINT CHK_PadronElectoral_Edad CHECK (Edad>18)
	, Estado BIT NOT NULL CONSTRAINT DF_Civil_Estado DEFAULT(0)
) WITH (DATA_COMPRESSION = PAGE) 

