CREATE TABLE [dbo].[Tramite]
(
	IdTipoTramite INT NOT NULL IDENTITY(1,1) CONSTRAINT PK_TipoTramite PRIMARY KEY CLUSTERED(IdTipoTramite)
	, Descripcion VARCHAR (256) NOT NULL
	, Estado BIT NOT NULL CONSTRAINT DF_TipoTramite_Estado DEFAULT(0)
) WITH (DATA_COMPRESSION = PAGE)
